baseURL = "http://gardener-matilda-80837.netlify.com/"
languageCode = "en-us"
title = "Personal site of Designer & Developer Al-jerreau Davids | Jero.co"
googleAnalytics = "UA-123-45"
theme = "jeroCo"